<?php

namespace TaskPlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function getUsersCategories($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT c FROM TaskPlannerBundle:Category c WHERE c.user = :id');
        $query->setParameter('id', $id);
        return $query->getResult();
    }

}
