<?php

namespace TaskPlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaryRepository extends EntityRepository
{
        //napisać funkcję do oznaczania zadan jako zakończone
    
    public function findCommentariesByTaskId($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT c FROM TaskPlannerBundle:Commentary c WHERE c.task = :id ORDER BY c.date DESC');
        $query->setParameter('id', $id);
        return $query->getResult();
    }
}
