<?php

namespace TaskPlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository {

    public function getTasksByCategory($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT p FROM TaskPlannerBundle:Person p WHERE p.user = :id ORDER BY p.name');
        $query->setParameter('id', $id);
        return $query->getResult();
    }

}
