<?php

namespace TaskPlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository {

    public function getPersonalTasks($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT t FROM TaskPlannerBundle:Task t WHERE t.user = :id');
        $query->setParameter('id', $id);
        return $query->getResult();
    }

    public function getTasksForToday($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT t FROM TaskPlannerBundle:Task t WHERE t.user = :id AND t.deadline = CURRENT_DATE()');
        $query->setParameter('id', $id);
        return $query->getResult();
    }
    

    public function getDelayedTasks() {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT t FROM TaskPlannerBundle:Task t WHERE t.deadline < CURRENT_DATE()');
        //$query->setParameter('id', $id);
        return $query->getResult();
    }
    
    public function getDelayedTasksForConcreteUser($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT t FROM TaskPlannerBundle:Task t WHERE t.user = :id AND t.deadline < CURRENT_DATE()');
        $query->setParameter('id', $id);
        return $query->getResult();
    }

}
