<?php

namespace TaskPlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository {

    public function getPersonalTasks($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT t FROM TaskPlannerBundle:Task t WHERE t.user = :id');
        $query->setParameter('id', $id);
        return $query->getResult();
    }
    
    //napisać funkcję do oznaczania zadan jako zakończone
    
    public function markTaskAsCompleted($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('UPDATE TaskPlannerBundle:Task t SET t.status = 1 WHERE t.id = :id');
        $query->setParameter('id', $id);
        return $query->execute();
        
        
    }

}
